chore(global): apply patches from termux branch
See-Also: 00aa74c8255465f7a785dcc0b0f32f44bc0b2886
See-Also: cbeb6b6b8589f9e3bca51b838a8fbf919aca2a8e
Signed-off-by: Andrei Jiroh Halili <ajhalili2006@andreijiroh.xyz>

diff --git a/.config/yadm/bootstrap b/.config/yadm/bootstrap
--- a/.config/yadm/bootstrap
+++ b/.config/yadm/bootstrap
@@ -8,18 +8,23 @@
 
 set -eu
 
+if [[ $DEBUG != "" ]]; then
+  set -x
+fi
+
 # Directory to look for bootstrap executables in
 BOOTSTRAP_D="${BASH_SOURCE[0]}.d"
 
 if [[ ! -d "$BOOTSTRAP_D" ]]; then
-    echo "Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
+    echo "[bootstrap] Error: bootstrap directory '$BOOTSTRAP_D' not found" >&2
     exit 1
 fi
 
 find -L "$BOOTSTRAP_D" -type f | sort | while IFS= read -r bootstrap; do
     if [[ -x "$bootstrap" && ! "$bootstrap" =~ "##" && ! "$bootstrap" =~ "~$" ]]; then
+        echo "[bootstrap] running $bootstrap"
         if ! "$bootstrap"; then
-            echo "Error: bootstrap '$bootstrap' failed" >&2
+            echo "[bootstrap] Error: bootstrap '$bootstrap' failed" >&2
             exit 1
         fi
     fi
